#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='es_ES.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $HOME/bin
  $HOME/.composer/vendor/bin
  # $(brew --prefix coreutils 2> /dev/null)/libexec/gnubin # on failure, see next stmt
  # $(brew --prefix gnu-sed 2> /dev/null)/libexec/gnubin # on failure, see next stmt
  # $(brew --prefix gnu-tar 2> /dev/null)/libexec/gnubin # on failure, see next stmt
  $path
)

# this removes whatever is not a directory or doesn't exist
# it lets me modify path in different OSes with less worries
path=($^path(N))

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-i -M -R -w -z-8'

# Set the Less input preprocessor. YES SYNTAX HIGHLIGHT YES YES YES

# Try source-highlight. It can call lesspipe if appropiate
if (( $#commands[(i)src-hilite-lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)src-hilite-lesspipe(|.sh)] %s 2>&-"

# Try both `lesspipe` and `lesspipe.sh`. It can call pygmentize if
# properly configured and appropiate
elif (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"

# Try pygmentize
elif (( $#commands[pygmentize] )); then
  export LESSOPEN="| $commands[pygmentize] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
