#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
    . "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"

    # source custom completions
    . "${ZDOTDIR:-$HOME}/.zprezto/custom/completions/tmuxinator.zsh"
fi

# Customize to your needs...
alias please="/usr/bin/sudo "
alias grep="grep --color=always"

if (( $+commands[nvim] )); then
    alias vim="nvim"
fi

function sshmount() {
    command -v sshfs || { echo 'sshfs could not be found.' && return 1; }

    sshfs "$1" "$2"                                  \
        -o reconnect                                 \
        -o allow_other                               \
        -o uid=$(id -u)                              \
        -o gid=$(id -g)                              \
        -o idmap=user                                \
        -o IdentityFile=${3:="$HOME/.ssh/id_rsa"}
}

# if phpbrew, source
# this must go before the mac block
if [ -f ~/.phpbrew/bashrc ]; then
    source ~/.phpbrew/bashrc &> /dev/null
fi

# Mac OS especific
if [[ "$OSTYPE" == darwin* ]]; then

    # Homebrew
    if type brew &> /dev/null; then
        ( brew update && brew upgrade; ) &> /dev/null &!
    else
        url="https://raw.githubusercontent.com/Homebrew/install/master/install"
        ( ruby -e "$(curl -fsSL "$url" )" &> /dev/null; ) &!
    fi

    # only if `homebrew` is installed
    if command -v brew >/dev/null 2>&1; then
        # Load rupa's z if installed
        if [ -f $(brew --prefix)/etc/profile.d/z.sh ]; then
            [ -f "$HOME/.z" ] || touch "$HOME/.z"
            . $(brew --prefix)/etc/profile.d/z.sh
        fi
    fi

    # set java home
    export JAVA_HOME=$(/usr/libexec/java_home -v 11 2> /dev/null)

    # phpbrew related for mac
    { command -v phpbrew  && phpbrew lookup-prefix homebrew } &> /dev/null

    # alias for vlc
    vlc_path='/Applications/VLC.app/Contents/MacOS/VLC'
    if [ -x "$vlc_path" ]; then
      alias vlc="$vlc_path"
    fi
    unset -v vlc_path
fi

# up; will be sourced on the next run
if command -v curl &> /dev/null; then
  if [ -f "$HOME/.config/up/up.sh" ]; then
    . "$HOME/.config/up/up.sh"
  else
    (                                                                       \
      curl --create-dirs -so "$HOME/.config/up/up.sh"                       \
      https://raw.githubusercontent.com/shannonmoeller/up/master/up.sh      \
    ) &!
  fi
fi

# thefuck
command -v thefuck &> /dev/null && eval "$(thefuck --alias)" && unsetopt correct

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# final options
unsetopt nomatch # fix extendedglob git log HEAD^ issues


function sep() {
    print $'\n\n\n\n'
    echo $(printf '=%.0s' {1..$(tput cols)})
    print $'\n\n\n\n'
}

isNpmOn=
function npmToggle () {
    # this shadows npm
    if $isNpmOn; then
        function npm() {
            # don't log the first time
            # (by detecting that the value is not initialized)
            if [ -n "$isNpmOn" ]; then
                echo '"npm" is now disabled; use "npmToggle" to enable it.'
            fi
        }
        npm

        isNpmOn=false
    # this unsets our shadowing function and makes npm accessible
    else
        unset -f npm
        isNpmOn=true

        echo '"npm" is now enabled; use "npmToggle" to disable it.'
    fi
}

# toggle npm off
npmToggle

alias n='pnpm'
alias x='pnpx --no-install'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
POWERLEVEL9K_MODE='nerdfont-complete'
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
